// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAYOeaM_UT8A6NJvo2poIgozUjzTUgLFN4',
  appId: '1:611132764098:android:7162c22350f14b723f305b',
  messagingSenderId: '611132764098',
  projectId: 'harajsyria',
  databaseURL: 'https://harajsyria-default-rtdb.firebaseio.com',
  storageBucket: 'harajsyria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
        apiKey: 'AIzaSyAChlGnjY7Jk_CyRKfIL9QnB2P-Lljs5zY',
        appId: '1:611132764098:ios:7a580311401da8aa3f305b',
        messagingSenderId: '611132764098',
        projectId: 'harajsyria',
        databaseURL: 'https://harajsyria-default-rtdb.firebaseio.com',
        storageBucket: 'harajsyria.firebasestorage.app',
        iosBundleId: 'com.haraj.syria.app.harajSyria',
  );
}
